[window]
padding.x = 10
padding.y = 10
dimensions.columns = 120
dimensions.lines = 40
dynamic_padding = false
decorations = "buttonless"
opacity = 0.9
blur = true
[font]
size = 16
normal = { family = "Jetbrains Mono", style = "Regular" }
